
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: environment
        description: "The envronment where dbt is writing to"
        tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: environment
        description: "The envronment where dbt is writing to"
        tests:
          - unique
          - not_null
